"""
NETWER — PDF report builder.

Builds a branded PDF network report from collected data. Which sections
are included is controlled by a `sections` set, so the Report page can
offer checkboxes (Network / System / Devices / Connectivity).

Data is gathered by report_data.collect() (separate module, runs in a
worker); this module only turns that data into a PDF. Keeping generation
separate from the UI means the same builder could back a CLI or scheduled
export later.
"""

import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether
)

# Brand palette (print-friendly versions of the app theme)
C_HEADER = colors.HexColor("#111830")
C_ACCENT = colors.HexColor("#2f6fed")
C_ACCENT_LT = colors.HexColor("#4d9bff")
C_SUCCESS = colors.HexColor("#1f9d57")
C_WARNING = colors.HexColor("#c77d16")
C_DANGER = colors.HexColor("#d13b34")
C_TEXT = colors.HexColor("#1a2233")
C_MUTED = colors.HexColor("#6b7690")
C_ROW_ALT = colors.HexColor("#f2f5fb")
C_BORDER = colors.HexColor("#dce3ef")

_ASSETS = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets")
LOGO_WHITE = os.path.join(_ASSETS, "logo", "report_logo_white.png")

# All known sections, in render order
ALL_SECTIONS = ["network", "system", "devices", "connectivity", "port_scan"]
SECTION_LABELS = {
    "network": "Network Configuration",
    "system": "System Information",
    "devices": "Connected Devices",
    "connectivity": "Connectivity Test",
    "port_scan": "Port Scan",
}


def _header_footer(canvas, doc):
    w, h = A4
    canvas.saveState()
    canvas.setFillColor(C_HEADER)
    canvas.rect(0, h - 42 * mm, w, 42 * mm, fill=1, stroke=0)
    try:
        canvas.drawImage(LOGO_WHITE, 18 * mm, h - 33 * mm,
                         width=20 * mm, height=20 * mm, mask='auto')
    except Exception:
        pass
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 22)
    canvas.drawString(44 * mm, h - 22 * mm, "NETWER")
    canvas.setFont("Helvetica", 11)
    canvas.setFillColor(C_ACCENT_LT)
    canvas.drawString(44 * mm, h - 28 * mm, "Network Diagnostic Report")
    canvas.setFillColor(colors.HexColor("#9fb0d0"))
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(w - 18 * mm, h - 22 * mm,
                           datetime.now().strftime("%Y-%m-%d %H:%M"))
    canvas.drawRightString(w - 18 * mm, h - 27 * mm, "NETWER v4.0")
    canvas.setStrokeColor(C_BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(18 * mm, 15 * mm, w - 18 * mm, 15 * mm)
    canvas.setFillColor(C_MUTED)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(18 * mm, 10 * mm,
                      "Generated by NETWER — Network Diagnostic Suite")
    canvas.drawRightString(w - 18 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _section_title(text):
    style = ParagraphStyle("SectionTitle", fontName="Helvetica-Bold",
                           fontSize=11, textColor=C_ACCENT,
                           spaceBefore=6, spaceAfter=4, leading=14)
    return Paragraph(text.upper(), style)


def _device_display_name(dev):
    """Best available name for a device: real hostname, else the vendor
    (e.g. 'LG Electronics'), else the IP. Mirrors the dashboard's Top
    Devices logic so the PDF never prints a bare 'Unknown'."""
    hostname = (dev.get("hostname") or "").strip()
    if hostname and hostname.lower() not in ("unknown", "?", ""):
        return hostname
    vendor = (dev.get("vendor") or "").strip()
    if vendor and vendor.lower() != "unknown":
        return vendor
    return dev.get("ip", "") or "—"


def _kv_table(rows):
    data = [[k, v if v not in (None, "") else "\u2014"] for k, v in rows]
    # splitByRow=0 forbids the table from breaking across pages. KeepTogether
    # alone isn't enough — a Table will happily split itself unless told not
    # to, which is what left half a table stranded on the previous page.
    t = Table(data, colWidths=[45 * mm, None], splitByRow=0, repeatRows=0)
    style = [
        ("FONTNAME", (0, 0), (0, -1), "Helvetica"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR", (0, 0), (0, -1), C_MUTED),
        ("TEXTCOLOR", (1, 0), (1, -1), C_TEXT),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, C_BORDER),
    ]
    for i in range(len(data)):
        if i % 2 == 0:
            style.append(("BACKGROUND", (0, i), (-1, i), C_ROW_ALT))
    t.setStyle(TableStyle(style))
    return t


def _grid_table(header, rows, success_col=None, col_widths=None):
    data = [header] + rows
    # splitByRow=0 forbids the table from breaking across pages — KeepTogether
    # alone isn't enough, because a Table will still split itself unless told
    # not to. That's what stranded half a table on the previous page.
    # repeatRows=1 keeps the header with the rows if a table is ever so long
    # that ReportLab has no choice but to move it wholesale to a new page.
    t = Table(data, colWidths=col_widths, splitByRow=0, repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), C_HEADER),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("TEXTCOLOR", (0, 1), (-1, -1), C_TEXT),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, C_BORDER),
        ("BOX", (0, 0), (-1, -1), 0.5, C_BORDER),
    ]
    if success_col is not None:
        style.append(("TEXTCOLOR", (success_col, 1), (success_col, -1), C_SUCCESS))
        style.append(("FONTNAME", (success_col, 1), (success_col, -1), "Helvetica-Bold"))
    for i in range(1, len(data)):
        if i % 2 == 0:
            style.append(("BACKGROUND", (0, i), (-1, i), C_ROW_ALT))
    t.setStyle(TableStyle(style))
    return t


def build_report(path, data: dict, sections=None):
    """Build the PDF at `path`.

    data: dict with keys 'network', 'system', 'devices', 'connectivity',
          'summary' (each optional).
    sections: iterable of section keys to include; defaults to all.
    """
    if sections is None:
        sections = ALL_SECTIONS
    sections = [s for s in ALL_SECTIONS if s in sections]

    doc = SimpleDocTemplate(
        path, pagesize=A4,
        topMargin=44 * mm, bottomMargin=20 * mm,
        leftMargin=18 * mm, rightMargin=18 * mm,
    )
    styles = getSampleStyleSheet()
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9.5,
                          textColor=C_TEXT, leading=13)
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8.5,
                           textColor=C_MUTED, leading=12)

    story = [Paragraph(
        "This report summarizes the current network configuration, "
        "connectivity status, and connected devices for the scanned system.",
        body), Spacer(1, 6)]

    # Summary strip (always shown if we have summary data)
    summary = data.get("summary", {})
    if summary:
        chip = Table([[
            Paragraph(f"<b>Internet</b><br/>{summary.get('internet','—')}", small),
            Paragraph(f"<b>Avg Ping</b><br/>{summary.get('ping','—')}", small),
            Paragraph(f"<b>Packet Loss</b><br/>{summary.get('loss','—')}", small),
            Paragraph(f"<b>Devices</b><br/>{summary.get('devices','—')}", small),
        ]], colWidths=[None] * 4)
        chip.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), C_ROW_ALT),
            ("BOX", (0, 0), (-1, -1), 0.5, C_BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, C_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ]))
        story.append(chip)
        story.append(Spacer(1, 10))

    # Network Configuration
    if "network" in sections and data.get("network"):
        n = data["network"]
        # KeepTogether: a section's heading and its table must never be
        # split across a page break — ReportLab would otherwise strand the
        # heading at the bottom of one page and the rows on the next.
        story.append(KeepTogether([
            _section_title("Network Configuration"),
            _kv_table([
                ("Adapter", n.get("name", "")),
                ("Description", n.get("description", "")),
                ("IPv4 Address", n.get("ipv4", "")),
                ("Subnet Mask", n.get("subnet_mask", "")),
                ("Gateway", n.get("gateway", "")),
                ("DNS Servers", n.get("dns", "")),
                ("Public IP", n.get("public_ip", "")),
                ("MAC Address", n.get("mac", "")),
                ("DHCP", n.get("dhcp", "")),
                ("Link Speed", n.get("link_speed", "")),
            ]),
        ]))
        story.append(Spacer(1, 10))

    # System Information
    if "system" in sections and data.get("system"):
        s = data["system"]
        story.append(KeepTogether([
            _section_title("System Information"),
            _kv_table([
                ("Computer Name", s.get("computer", "")),
                ("Operating System", s.get("os", "")),
                ("Processor", s.get("cpu", "")),
                ("Total RAM", f"{s.get('ram', '')} GB" if s.get("ram") else ""),
                ("System Uptime", s.get("uptime", "")),
            ]),
        ]))
        story.append(Spacer(1, 10))

    # Connected Devices
    if "devices" in sections and data.get("devices"):
        devs = data["devices"]
        rows = [[_device_display_name(d),
                 d.get("ip", ""), d.get("mac", ""),
                 d.get("vendor", "") if d.get("vendor") != "Unknown" else "—",
                 "Online"] for d in devs]
        story.append(KeepTogether([
            _section_title("Connected Devices"),
            _grid_table(
                ["Hostname", "IP Address", "MAC Address", "Vendor", "Status"],
                rows, success_col=4,
                col_widths=[38 * mm, 30 * mm, 34 * mm, 30 * mm, 20 * mm]),
        ]))
        story.append(Spacer(1, 10))

    # Connectivity Test
    if "connectivity" in sections and data.get("connectivity"):
        pings = data["connectivity"]
        rows = [[p.get("label", ""), p.get("ip", ""),
                 f"{p.get('avg','')} ms", f"{p.get('min','')} ms",
                 f"{p.get('max','')} ms", f"{p.get('loss','')}%"]
                for p in pings]
        story.append(KeepTogether([
            _section_title("Connectivity Test"),
            _grid_table(
                ["Target", "Address", "Avg", "Min", "Max", "Loss"],
                rows, success_col=5,
                col_widths=[35 * mm, 32 * mm, 22 * mm, 22 * mm, 22 * mm, 20 * mm]),
        ]))
        story.append(Spacer(1, 10))

    # Port Scan (from the last scan run in the Port Scanner)
    if "port_scan" in sections and data.get("port_scan"):
        ps = data["port_scan"]
        results = ps.get("results", [])
        target = ps.get("target", "")
        dtype = ps.get("device_type", "")
        counts = ps.get("counts", {})
        subtitle = (f"Target {target}"
                    + (f"  ·  detected as {dtype}" if dtype else "")
                    + (f"  ·  {counts.get('open', 0)} open, "
                       f"{counts.get('filtered', 0)} filtered"
                       if counts else ""))
        rows = [[str(r.get("port", "")), r.get("service", ""),
                 r.get("protocol", "TCP"),
                 (r.get("banner", "") or "")[:40]]
                for r in results]
        if rows:
            story.append(KeepTogether([
                _section_title("Port Scan"),
                Paragraph(subtitle, small),
                Spacer(1, 4),
                _grid_table(
                    ["Port", "Service", "Protocol", "Version / Banner"],
                    rows,
                    col_widths=[18 * mm, 40 * mm, 24 * mm, 66 * mm]),
            ]))
            story.append(Spacer(1, 10))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return path
